
import Script from "next/script";
import type { Metadata } from "next";
import { cookies } from "next/headers";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import CartProviderBridge from "./shared/CartProviderBridge";
import ClientToastWrapper from "./shared/ClientToastWrapper";
import PageFooter from "./PageFooter";
import { verifyAuthToken } from "@/lib/jwt";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const sessionToken = cookieStore.get("asmyne_auth")?.value;
  const session = sessionToken ? verifyAuthToken(sessionToken) : null;
  const cartPrefix = session && typeof session !== "string" && session.sub ? `cart:${session.sub}` : "cart:guest";

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head />
      <body className="relative min-h-full flex flex-col overflow-x-hidden text-gray-800 bg-gray-50">
        <div aria-hidden="true" className="pointer-events-none fixed inset-0 z-0 faq-water-ripples" />
        <div aria-hidden="true" className="pointer-events-none fixed inset-x-0 top-0 h-[45vh] z-0 faq-water-sheen" />
        {/* ToastProvider must wrap CartProvider so CartContext can use toasts */}
        <ClientToastWrapper>
          <CartProviderBridge userCartPrefix={cartPrefix}>
            <div className="relative z-10">
              {children}
            </div>
          </CartProviderBridge>
        </ClientToastWrapper>
      </body>
    </html>
  );
}

